# -*- coding: utf-8 -*-
"""poguise+_+objects.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M2ECKFCaY5O3IMxD8MTFyVhSh5Hbai_q
"""

import os
import sys
import shlex
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed

import google.auth
from google.colab import auth
from google.auth.transport.requests import Request

REPO_URL = "https://github.com/michelsedgh/pog.git"
REPO_DIR = "/content/pog"

SCRATCH_ROOT = "/mnt/local-scratch" if os.path.isdir("/mnt/local-scratch") else "/content"

DATA_DIR = f"{SCRATCH_ROOT}/poguise_data"
FRAME_ARCHIVE_DIR = f"{DATA_DIR}/frame_archives"
FRAME_MOUNT_ROOT = f"{SCRATCH_ROOT}/toyota_frame_mounts"
FRAME_UNION_DIR = f"{DATA_DIR}/frames"

SKELETON_FILE_ID = "1CPXzaRMRLg3rQg13Pn4ZHIjg7Bud6Wgi"

FRAMES_PART1_TAR_FILE_ID = "1bOni09lR3HS48FYQCq4L-6caJGB8ELuV"
FRAMES_PART1_SQLITE_FILE_ID = "1MgAlhDfPcSSdrCHkVxxzxA3s98dMszae"
FRAMES_PART2_TAR_FILE_ID = "1BGn2PAyNrH2k59snixN5z7eTFFVEmkBW"
FRAMES_PART2_SQLITE_FILE_ID = "1Qy8wk3_y2dnSKEuNCMsM3tV3LrlgVY1S"

OBJECT_CACHE_FILE_ID = "1kmCdEhfH_LUBNDlC4C1pUXtwz9PEORyp"
RESUME_CKPT_FILE_ID = "1RcZZLkaonD8nmD6Bf_5HSTSU3aYaAsO2"
HARD_NEGATIVES_FILE_ID = "13u7AZ5-MRrQMe6k2wwK1HW3S7kmn8_7v"

SKELETON_ZIP = f"{DATA_DIR}/toyota_smarthome_skeleton_v1.2.zip"
RESUME_CKPT_PATH = f"{DATA_DIR}/object_v2_resume_epoch.ckpt"
OBJECT_DETECTOR_CACHE = f"{DATA_DIR}/toyota_rfdetr_2xlarge_coco19_full.jsonl"
HARD_NEGATIVE_MANIFEST = f"{DATA_DIR}/hard_negatives.json"

FRAMES_PART1_TAR = f"{FRAME_ARCHIVE_DIR}/toyota_smarthome_frames_part001.tar"
FRAMES_PART1_SQLITE = f"{FRAME_ARCHIVE_DIR}/toyota_smarthome_frames_part001.tar.index.sqlite"
FRAMES_PART2_TAR = f"{FRAME_ARCHIVE_DIR}/toyota_smarthome_frames_part002.tar"
FRAMES_PART2_SQLITE = f"{FRAME_ARCHIVE_DIR}/toyota_smarthome_frames_part002.tar.index.sqlite"

FRAME_COUNT_CACHE = f"{DATA_DIR}/toyota_frame_counts.json"

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(FRAME_ARCHIVE_DIR, exist_ok=True)
os.makedirs(FRAME_MOUNT_ROOT, exist_ok=True)

def run(cmd, label=None, cwd=None):
    print("\n" + "=" * 90, flush=True)
    if label:
        print(label, flush=True)
    print("$ " + " ".join(shlex.quote(str(x)) for x in cmd), flush=True)
    print("=" * 90, flush=True)
    subprocess.run(cmd, cwd=cwd, check=True)

run(["apt-get", "update"], "Updating apt")
run(["apt-get", "install", "-y", "aria2", "ffmpeg", "fuse"], "Installing system tools")

if os.path.isdir(REPO_DIR):
    run(["git", "-C", REPO_DIR, "fetch", "origin", "main"], "Fetching repo")
    run(["git", "-C", REPO_DIR, "checkout", "main"], "Checking out main")
    run(["git", "-C", REPO_DIR, "pull", "--ff-only", "origin", "main"], "Pulling latest main")
else:
    run(["git", "clone", "--branch", "main", REPO_URL, REPO_DIR], "Cloning repo")

run(["git", "-C", REPO_DIR, "log", "-1", "--oneline"], "Current repo commit")

run([sys.executable, "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel"], "Upgrading pip tooling")

run([
    sys.executable, "-m", "pip", "install", "--progress-bar", "on",
    "pytorch-lightning==2.5.1",
    "torchmetrics==1.7.0",
    "timm==1.0.11",
    "av==13.1.0",
    "opencv-python-headless==4.10.0.84",
    "pandas",
    "scipy",
    "matplotlib",
    "tqdm",
    "einops",
    "json-tricks",
    "munkres",
    "addict",
    "yapf",
    "rich",
    "ratarmount",
    "cvxpy",
    "ecos",
], "Installing core Python dependencies + Nash-MTL solver")

run([
    sys.executable, "-m", "pip", "install", "--progress-bar", "on",
    "mmengine==0.10.5",
    "mmcv-lite==2.2.0",
], "Installing OpenMMLab base packages")

run([
    sys.executable, "-m", "pip", "install", "--progress-bar", "on",
    "mmpose==1.3.2",
    "--no-deps",
], "Installing mmpose without xtcocotools")

print("\nVerifying imports...", flush=True)
import torch
import torchvision
import pytorch_lightning
import timm
import cvxpy as cp
from mmpose.codecs import UDPHeatmap

print("torch:", torch.__version__, "cuda:", torch.cuda.is_available(), flush=True)
print("torchvision:", torchvision.__version__, flush=True)
print("pytorch_lightning:", pytorch_lightning.__version__, flush=True)
print("cvxpy:", cp.__version__, flush=True)
print("cvxpy solvers:", cp.installed_solvers(), flush=True)
print("UDPHeatmap OK:", UDPHeatmap, flush=True)

if "ECOS" not in cp.installed_solvers():
    raise RuntimeError("ECOS solver is missing. Nash-MTL would silently fall back to equal weights.")

print("\nAuthenticating Google Drive...", flush=True)
auth.authenticate_user()
creds, _ = google.auth.default()
creds.refresh(Request())
token = creds.token

def download_drive_file(file_id, output_path):
    if os.path.exists(output_path) and os.path.getsize(output_path) > 0:
        print(f"Found existing file: {output_path} ({os.path.getsize(output_path) / 1e9:.2f} GB)", flush=True)
        return output_path

    url = f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media"
    run([
        "aria2c",
        "-x", "16",
        "-s", "16",
        "-j", "16",
        "--file-allocation=none",
        "--summary-interval=10",
        "--console-log-level=notice",
        "--header", f"Authorization: Bearer {token}",
        "-o", os.path.basename(output_path),
        "-d", os.path.dirname(output_path),
        url,
    ], f"Downloading {os.path.basename(output_path)}")
    return output_path

downloads = [
    (SKELETON_FILE_ID, SKELETON_ZIP),
    (FRAMES_PART1_TAR_FILE_ID, FRAMES_PART1_TAR),
    (FRAMES_PART1_SQLITE_FILE_ID, FRAMES_PART1_SQLITE),
    (FRAMES_PART2_TAR_FILE_ID, FRAMES_PART2_TAR),
    (FRAMES_PART2_SQLITE_FILE_ID, FRAMES_PART2_SQLITE),
    (OBJECT_CACHE_FILE_ID, OBJECT_DETECTOR_CACHE),
    (RESUME_CKPT_FILE_ID, RESUME_CKPT_PATH),
    (HARD_NEGATIVES_FILE_ID, HARD_NEGATIVE_MANIFEST),
]

print("\nDownloading Drive files concurrently...", flush=True)
with ThreadPoolExecutor(max_workers=8) as executor:
    futures = [executor.submit(download_drive_file, file_id, path) for file_id, path in downloads]
    for future in as_completed(futures):
        print("Ready:", future.result(), flush=True)

def unmount_if_mounted(path):
    subprocess.run(["fusermount", "-u", path], check=False)
    subprocess.run(["umount", path], check=False)

def mount_tar(tar_path, sqlite_path, mount_path):
    os.makedirs(mount_path, exist_ok=True)
    unmount_if_mounted(mount_path)
    run([
        "ratarmount",
        "--index-file", sqlite_path,
        tar_path,
        mount_path,
    ], f"Mounting {os.path.basename(tar_path)}")

PART1_MOUNT = f"{FRAME_MOUNT_ROOT}/part001"
PART2_MOUNT = f"{FRAME_MOUNT_ROOT}/part002"

mount_tar(FRAMES_PART1_TAR, FRAMES_PART1_SQLITE, PART1_MOUNT)
mount_tar(FRAMES_PART2_TAR, FRAMES_PART2_SQLITE, PART2_MOUNT)

if os.path.islink(FRAME_UNION_DIR) or os.path.exists(FRAME_UNION_DIR):
    run(["rm", "-rf", FRAME_UNION_DIR], "Removing old frame union directory")

os.makedirs(FRAME_UNION_DIR, exist_ok=True)

for root in [f"{PART1_MOUNT}/frames", f"{PART2_MOUNT}/frames"]:
    if not os.path.isdir(root):
        raise RuntimeError(f"Mounted tar does not contain frames directory: {root}")

    for name in os.listdir(root):
        src = os.path.join(root, name)
        dst = os.path.join(FRAME_UNION_DIR, name)
        if os.path.exists(dst):
            raise RuntimeError(f"Duplicate video frame directory: {name}")
        os.symlink(src, dst)

frame_dir_count = len([
    name for name in os.listdir(FRAME_UNION_DIR)
    if os.path.isdir(os.path.join(FRAME_UNION_DIR, name))
])
print("Unified frame dirs:", frame_dir_count, flush=True)
if frame_dir_count != 16115:
    raise RuntimeError(f"Expected 16115 frame dirs, got {frame_dir_count}")

sample_dirs = sorted(os.listdir(FRAME_UNION_DIR))[:3]
print("Sample frame dirs:", sample_dirs, flush=True)
for sample in sample_dirs:
    sample_path = os.path.join(FRAME_UNION_DIR, sample)
    sample_frames = sorted(os.listdir(sample_path))[:3]
    print(sample, sample_frames, flush=True)

for path in [SKELETON_ZIP, OBJECT_DETECTOR_CACHE, RESUME_CKPT_PATH, HARD_NEGATIVE_MANIFEST]:
    if not os.path.exists(path) or os.path.getsize(path) <= 0:
        raise RuntimeError(f"Missing or empty required file: {path}")
    print(f"Verified: {path} ({os.path.getsize(path) / 1e9:.2f} GB)", flush=True)

with open("/content/poguise_colab_env.sh", "w") as f:
    f.write(f"""export REPO_DIR='{REPO_DIR}'
export DATA_DIR='{DATA_DIR}'
export SKELETON_ZIP='{SKELETON_ZIP}'
export CKPT_PATH='{RESUME_CKPT_PATH}'
export RESUME_CKPT_PATH='{RESUME_CKPT_PATH}'
export OBJECT_DETECTOR_CACHE='{OBJECT_DETECTOR_CACHE}'
export HARD_NEGATIVE_MANIFEST='{HARD_NEGATIVE_MANIFEST}'
export FRAME_COUNT_CACHE='{FRAME_COUNT_CACHE}'
export TOYOTA_FRAME_SOURCE='frames'
export TOYOTA_FRAMES_DIR='{FRAME_UNION_DIR}'
export FRAMES_PART1_TAR='{FRAMES_PART1_TAR}'
export FRAMES_PART1_SQLITE='{FRAMES_PART1_SQLITE}'
export FRAMES_PART2_TAR='{FRAMES_PART2_TAR}'
export FRAMES_PART2_SQLITE='{FRAMES_PART2_SQLITE}'
export FRAME_MOUNT_ROOT='{FRAME_MOUNT_ROOT}'
""")

print("\nSetup complete.", flush=True)
print("Repo:", REPO_DIR, flush=True)
print("Data:", DATA_DIR, flush=True)
print("Frame source: frames", flush=True)
print("Frame union:", FRAME_UNION_DIR, flush=True)
print("Skeleton zip:", SKELETON_ZIP, flush=True)
print("Object cache:", OBJECT_DETECTOR_CACHE, flush=True)
print("Hard negatives:", HARD_NEGATIVE_MANIFEST, flush=True)
print("Resume checkpoint:", RESUME_CKPT_PATH, flush=True)

from pathlib import Path
from datetime import datetime
import os, sys, subprocess, shlex, select
import pandas as pd

if "REPO_DIR" not in globals():
    env_file = Path("/content/poguise_colab_env.sh")
    if not env_file.is_file():
        raise RuntimeError("Run Cell 1 first; /content/poguise_colab_env.sh is missing.")
    for line in env_file.read_text().splitlines():
        if not line.startswith("export ") or "=" not in line:
            continue
        key, value = line[len("export "):].split("=", 1)
        globals()[key] = shlex.split(value)[0]

os.chdir(REPO_DIR)

def run_checked(cmd, label=None):
    print("\n" + "=" * 100, flush=True)
    if label:
        print(label, flush=True)
    print("$ " + " ".join(shlex.quote(str(x)) for x in cmd), flush=True)
    print("=" * 100, flush=True)
    subprocess.run(cmd, cwd=REPO_DIR, check=True)

run_checked([
    sys.executable, "-m", "py_compile",
    "datasets/object_vocab.py",
    "datasets/toyota_action_taxonomy.py",
    "datasets/toyotasm.py",
    "models/factorized_interaction_action_head.py",
    "models/poguise.py",
    "modules/heatmap_module.py",
    "losses/poguiseplus_losses.py",
    "train.py",
    "summarize_interaction_metrics.py",
    "utils/bisect_actor_tensorrt.py",
    "utils/export_actor_tensorrt.py",
    "utils/actor_model.py",
], "Compile check")

heatmap_source = Path("modules/heatmap_module.py").read_text()
if "safe_actions = actions.clamp(0, best_slot.shape[-1] - 1)" not in heatmap_source:
    raise RuntimeError(
        "The checked-out code is missing the validation diagnostic padded-label "
        "guard. Update the repo before starting this run."
    )

def latest_metrics_path(run_dir):
    paths = sorted(Path(run_dir).glob("version_*/metrics.csv"), key=lambda p: p.stat().st_mtime)
    return paths[-1] if paths else None

def completed_validation_epoch_count(metrics_path):
    if metrics_path is None or not Path(metrics_path).is_file():
        return 0
    try:
        raw = pd.read_csv(metrics_path)
    except Exception:
        return 0
    if "epoch" not in raw.columns:
        return 0
    val_cols = [c for c in ["val_loss", "val_f1", "val_acc_macro", "val_deploy_score"] if c in raw.columns]
    if not val_cols:
        return 0

    def last_nonnull(s):
        s = s.dropna()
        return s.iloc[-1] if len(s) else float("nan")

    df = raw.groupby("epoch", as_index=False).agg({c: last_nonnull for c in raw.columns if c != "epoch"})
    df = df.dropna(how="all", subset=val_cols)
    return len(df)

def summarize_run(run_dir, verbose=False):
    cmd = [sys.executable, "summarize_interaction_metrics.py", "--run", str(run_dir)]
    if verbose:
        cmd.append("--verbose")
    print("\n" + "=" * 100, flush=True)
    print("$ " + " ".join(shlex.quote(str(x)) for x in cmd), flush=True)
    print("=" * 100, flush=True)
    result = subprocess.run(cmd, cwd=REPO_DIR, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    print(result.stdout, flush=True)
    if result.returncode != 0:
        print("Summary not ready yet.", flush=True)

def drain_training_output(proc):
    while True:
        ready, _, _ = select.select([proc.stdout], [], [], 0)
        if not ready:
            break
        line = proc.stdout.readline()
        if not line:
            break
        print(line, end="", flush=True)

def run_training_with_epoch_summaries(cmd, run_name, epoch_dir, poll_secs=20):
    run_dir = Path(DATA_DIR) / "checkpoints" / run_name
    epoch_dir = Path(epoch_dir)
    last_completed_val_count = 0
    last_ckpt_count = 0

    print("\nRUN_NAME:", run_name, flush=True)
    print("RUN_DIR:", run_dir, flush=True)
    print("EPOCH_DIR:", epoch_dir, flush=True)
    print("\n" + "=" * 100, flush=True)
    print("$ " + " ".join(shlex.quote(str(x)) for x in cmd), flush=True)
    print("=" * 100, flush=True)

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    proc = subprocess.Popen(
        cmd, cwd=REPO_DIR, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1, env=env,
    )

    while True:
        select.select([proc.stdout], [], [], poll_secs)
        drain_training_output(proc)

        ckpt_count = len(sorted(epoch_dir.glob("epoch=*.ckpt")))
        if ckpt_count > last_ckpt_count:
            last_ckpt_count = ckpt_count
            print(f"\nCheckpoint files seen: {ckpt_count}", flush=True)

        metrics_path = latest_metrics_path(run_dir)
        completed_count = completed_validation_epoch_count(metrics_path)
        if completed_count > last_completed_val_count:
            last_completed_val_count = completed_count
            print("\n" + "#" * 100, flush=True)
            print(f"SUMMARY AFTER {completed_count} COMPLETED VALIDATION EPOCH(S): {run_name}", flush=True)
            print("#" * 100, flush=True)
            summarize_run(run_dir, verbose=False)

        if proc.poll() is not None:
            drain_training_output(proc)
            for line in proc.stdout:
                print(line, end="", flush=True)
            break

    if proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, cmd)

    print("\nTRAINING DONE:", run_dir, flush=True)
    summarize_run(run_dir, verbose=True)
    return str(run_dir)

TS = datetime.now().strftime("%Y%m%d_%H%M%S")
RUN_NAME = f"actor_object_visualfallback_v1_deploybalanced_videomae_epoch20_{TS}"
EPOCH_DIR = str(Path(DATA_DIR) / "checkpoints" / RUN_NAME / "epoch_checkpoints")

cmd = [
    sys.executable, "-u", "train.py",

    "--pretrained", "DEFAULT",
    "--net_size", "b",

    "--dataset", "toyotasm",
    "--dataset_artifact", "toyotasm",
    "--data_dir", DATA_DIR,
    "--toyota_action_taxonomy", "product_v1",
    "--toyota_frame_source", "frames",
    "--toyota_skeleton_zip", SKELETON_ZIP,
    "--toyota_frame_count_cache", FRAME_COUNT_CACHE,
    "--toyota_object_cache_dir", f"{DATA_DIR}/toyota_preprocessed_cache/objects",
    "--toyota_landmark_cache_dir", f"{DATA_DIR}/toyota_preprocessed_cache/landmarks",
    "--toyota_split_source", "auto",
    "--toyota_val_fraction", "0.15",
    "--toyota_test_fraction", "0.0",

    "--num_classes", "26",
    "--n_landmarks", "13",
    "--hw_out_conv", "8",

    "--actor_prompt", "1",
    "--num_actor_tokens", "8",
    "--actor_presence_head", "1",
    "--presence_loss_weight", "0.05",

    "--actor_interaction_heatmaps", "1",

    # Fixed top-K runtime object proposals for the factorized interaction head.
    # This is not the removed scene-object-token trunk path.
    "--actor_object_factorized_head", "1",
    "--actor_object_slot_head", "0",
    "--num_scene_object_tokens", "32",
    "--num_object_classes", "19",
    "--actor_object_factorized_hidden_dim", "512",
    "--actor_object_factorized_relation_scale_init", "-1.00",
    "--actor_object_factorized_relation_logit_bound", "2.0",
    "--actor_object_factorized_max_relation_scale", "1.5",

    "--object_detector_cache", OBJECT_DETECTOR_CACHE,
    "--object_camera_allowlist", "tv_monitor=c05,c06",
    "--object_ignore_regions", "c03=0,0,0.26,0.42",
    "--object_conf_threshold", "0.25",

    "--object_token_box_jitter", "0.0",
    "--object_token_confidence_noise", "0.0",

    "--interaction_heatmap_size", "56",
    "--interaction_heatmap_sigma", "1.5",
    "--interaction_guided_sampling", "1",
    "--interaction_min_sampled_object_frames", "1",
    "--interaction_repair_radius_frames", "8",
    "--interaction_quality_min_actor_score", "1.0",
    "--interaction_quality_min_track_frames", "1",
    "--interaction_quality_min_track_coverage", "0.0",

    "--objectless_hard_negative_sampling", "1",
    "--objectless_hard_negative_min_sampled_object_frames", "2",

    "--freeze_backbone", "0",
    "--interaction_warmup_freeze_actor_path", "0",
    "--interaction_unfreeze_last_blocks", "0",

    "--class_balanced_sampler", "1",
    "--hard_negative_sampler", "1",
    "--hard_negative_manifest", HARD_NEGATIVE_MANIFEST,
    "--hard_negative_prob", "0.25",

    "--keep_rate", "0.6",
    "--keep_rate_merge", "0.3",
    "--merge_type", "sim",
    "--merge_mode", "0",
    "--sim_metric", "1",
    "--topk_type", "1",

    "--mixup", "0",

    "--grad_weights", "1",
    "--nash_update_weights_every", "20",
    "--nash_max_norm", "2.0",

    "--poguiseplus_heatmap_loss_weight", "1.0",
    "--poguiseplus_pose_heatmap_weight", "0.25",
    "--poguiseplus_interaction_heatmap_weight", "3.0",
    "--poguiseplus_heatmap_log_eps", "1e-6",
    "--poguiseplus_normalized_heatmap_loss", "1",
    "--poguiseplus_heatmap_mse_scale", "1000",

    "--motion_aux_loss_weight", "0.25",
    "--factorized_presence_loss_weight", "1.0",
    "--factorized_objectful_within_loss_weight", "0.5",
    "--object_slot_target_loss_weight", "1.0",
    "--object_slot_quality_loss_weight", "0.5",
    "--object_slot_quality_pos_weight", "1.0",
    "--object_slot_quality_neg_weight", "0.25",
    "--object_slot_quality_exact_neg_topk", "4",
    "--object_slot_quality_objectless_neg_topk", "8",
    "--object_action_confuser_loss_weight", "0.0",
    "--object_action_confuser_margin", "1.0",
    "--objectless_object_action_suppression_loss_weight", "0.5",
    "--teacher_object_drop_prob", "0.10",
    "--object_class_dropout_prob", "0.0",
    "--object_class_wrong_prob", "0.0",
    "--missing_object_full_ce_weight", "0.0",
    "--missing_object_confuser_weight", "0.50",
    "--missing_object_confuser_margin", "1.0",
    "--missing_object_visual_fallback_loss_weight", "0.10",

    "--toyota_pose_guided_sampling", "1",
    "--toyota_min_pose_frames", "1",
    "--toyota_synthetic_warmup_epochs", "2",
    "--toyota_synthetic_two_actor_prob", "0.30",
    "--toyota_synthetic_three_actor_prob", "0.0",
    "--toyota_synthetic_same_class_prob", "0.45",
    "--toyota_synthetic_confuser_prob", "0.65",

    "--batch_size", "32",
    "--accum_grad_batches", "2",

    "--max_epochs", "3",
    "--t_max_scheduler", "3",

    "--lr", "5e-5",
    "--lr_head", "5e-4",
    "--lr_head_hm", "5e-4",

    "--weight_decay", "0.04",
    "--weight_decay_head", "0.01",
    "--weight_decay_head_hm", "0.005",
    "--label_smoothing", "0.0",
    "--gradient_clip_val", "1.0",

    "--num_workers", "12",
    "--persistent_workers", "1",
    "--prefetch_factor", "2",
    "--precision", "bf16-mixed",
    "--accelerator", "gpu",
    "--gpus", "1",

    "--limit_val_batches", "1.0",
    "--check_val_every_n_epoch", "1",
    "--num_sanity_val_steps", "0",
    "--log_every_n_steps", "50",

    "--checkpoint_monitor", "val_deploy_score",
    "--checkpoint_mode", "max",
    "--checkpoint_filename", "{epoch:03d}-{val_deploy_score:.4f}-{val_f1:.4f}-{val_acc_macro:.4f}",
    "--save_top_k", "5",
    "--save_every_epoch_checkpoints", "1",
    "--epoch_checkpoint_dir", EPOCH_DIR,
    "--epoch_checkpoint_filename", "{epoch:03d}",

    "--default_root_dir", f"{DATA_DIR}/checkpoints",
    "--model_name", RUN_NAME,
]

bad_flags = {
    "--model_file",
    "--resume_from_checkpoint",
    "--scene_object_tokens",
    "--interaction_object_classes",
    "--actor_object_relation_layers",
    "--actor_object_relation_heads",
    "--actor_object_relation_hidden_dim",
    "--actor_object_relevance_gate_init",
    "--actor_object_action_fusion",
    "--actor_object_action_fusion_hidden_dim",
    "--actor_object_action_fusion_gate_init",
    "--object_token_dropout_prob",
    "--object_token_class_dropout_prob",
    "--poguiseplus_interaction_target_weight",
    "--poguiseplus_interaction_background_weight",
    "--aux_object_selection_loss_weight",
    "--object_selection_loss_weight",
    "--object_relevance_loss_weight",
    "--object_counterfactual_loss_weight",
    "--object_counterfactual_margin",
    "--object_counterfactual_eval",
    "--object_slot_ignore_missing_object",
    "--object_slot_unknown_exact_loss_weight",
    "--missing_object_ce_weight",
    "--objectful_presence_loss_weight",
    "--actor_object_slot_hidden_dim",
    "--actor_object_slot_attn_dim",
    "--actor_object_slot_num_visual_slots",
}
present_bad = sorted(flag for flag in bad_flags if flag in cmd)
if present_bad:
    raise RuntimeError(f"Deprecated/removed flags still present: {present_bad}")

required_flags = {
    "--toyota_action_taxonomy",
    "--poguiseplus_normalized_heatmap_loss",
    "--actor_object_factorized_head",
    "--actor_object_slot_head",
    "--motion_aux_loss_weight",
    "--factorized_presence_loss_weight",
    "--factorized_objectful_within_loss_weight",
    "--object_slot_target_loss_weight",
    "--object_slot_quality_loss_weight",
    "--object_slot_quality_pos_weight",
    "--object_slot_quality_neg_weight",
    "--object_slot_quality_exact_neg_topk",
    "--object_slot_quality_objectless_neg_topk",
    "--teacher_object_drop_prob",
    "--object_class_dropout_prob",
    "--object_class_wrong_prob",
    "--missing_object_full_ce_weight",
    "--missing_object_confuser_weight",
    "--missing_object_confuser_margin",
    "--missing_object_visual_fallback_loss_weight",
    "--object_action_confuser_loss_weight",
    "--object_action_confuser_margin",
    "--objectless_object_action_suppression_loss_weight",
    "--objectless_hard_negative_sampling",
    "--objectless_hard_negative_min_sampled_object_frames",
    "--merge_type",
    "--sim_metric",
    "--t_max_scheduler",
    "--label_smoothing",
    "--lr",
    "--lr_head",
    "--lr_head_hm",
    "--object_token_box_jitter",
    "--object_token_confidence_noise",
    "--actor_object_factorized_hidden_dim",
    "--actor_object_factorized_relation_scale_init",
    "--actor_object_factorized_relation_logit_bound",
    "--actor_object_factorized_max_relation_scale",
    "--checkpoint_monitor",
}
missing = sorted(flag for flag in required_flags if flag not in cmd)
if missing:
    raise RuntimeError(f"Required flags missing: {missing}")

checks = {
    "--pretrained": "DEFAULT",
    "--toyota_action_taxonomy": "product_v1",
    "--num_classes": "26",
    "--actor_object_factorized_head": "1",
    "--actor_object_slot_head": "0",
    "--checkpoint_monitor": "val_deploy_score",
    "--checkpoint_mode": "max",
    "--max_epochs": "3",
    "--t_max_scheduler": "3",
    "--merge_type": "sim",
    "--sim_metric": "1",
    "--lr": "5e-5",
    "--lr_head": "5e-4",
    "--lr_head_hm": "5e-4",
    "--label_smoothing": "0.0",
    "--poguiseplus_normalized_heatmap_loss": "1",
    "--poguiseplus_interaction_heatmap_weight": "3.0",
    "--motion_aux_loss_weight": "0.25",
    "--factorized_presence_loss_weight": "1.0",
    "--factorized_objectful_within_loss_weight": "0.5",
    "--object_slot_target_loss_weight": "1.0",
    "--object_slot_quality_loss_weight": "0.5",
    "--object_slot_quality_pos_weight": "1.0",
    "--object_slot_quality_neg_weight": "0.25",
    "--object_slot_quality_exact_neg_topk": "4",
    "--object_slot_quality_objectless_neg_topk": "8",
    "--object_action_confuser_loss_weight": "0.0",
    "--object_action_confuser_margin": "1.0",
    "--objectless_object_action_suppression_loss_weight": "0.5",
    "--teacher_object_drop_prob": "0.10",
    "--object_class_dropout_prob": "0.0",
    "--object_class_wrong_prob": "0.0",
    "--missing_object_full_ce_weight": "0.0",
    "--missing_object_confuser_weight": "0.50",
    "--missing_object_confuser_margin": "1.0",
    "--missing_object_visual_fallback_loss_weight": "0.10",
    "--object_token_box_jitter": "0.0",
    "--object_token_confidence_noise": "0.0",
    "--actor_object_factorized_hidden_dim": "512",
    "--actor_object_factorized_relation_scale_init": "-1.00",
    "--actor_object_factorized_relation_logit_bound": "2.0",
    "--actor_object_factorized_max_relation_scale": "1.5",
}
for flag, expected in checks.items():
    actual = cmd[cmd.index(flag) + 1]
    if actual != expected:
        raise RuntimeError(f"Expected {flag} {expected}, got {actual}")

for checkpoint_name in ("CKPT_PATH", "RESUME_CKPT_PATH"):
    checkpoint_path = globals().get(checkpoint_name)
    if checkpoint_path and checkpoint_path in cmd:
        raise RuntimeError(
            f"{checkpoint_name} is present in the training command. "
            "This cell must train from the original DEFAULT backbone, not an old checkpoint."
        )

run_dir = run_training_with_epoch_summaries(cmd, RUN_NAME, EPOCH_DIR, poll_secs=20)
print("RUN_DIR:", run_dir)
